#!/usr/bin/env python3
import sys


def main():
    # create .gitignore

    # create dockerfile
    # create docker-compose file
    # create requirements.txt

if __name__ == "__main__":
    main()

