#!/usr/bin/env python3
import sys
from shutil import copyfile


def main():
    # create .gitignore
    generate_gitignore()
    # create dockerfile
    generate_dockerfile()
    # create docker-compose file
    generate_dockercompose()
    # create requirements.txt
    generate_requirements()


def generate_gitignore(dst="."):
    src = "templates/.gitignore"
    copyfile(src, dst)


def generate_dockerfile():
    src = "templates/Dockerfile"
    copyfile(src, dst)


def generate_dockercompose():
    src = "templates/docker-compose.yml"
    copyfile(src, dst)


def generate_requirements():
    src = "templates/requirements.txt"
    copyfile(src, dst)


if __name__ == "__main__":
    main()

